--- #YAML:1.0
name:                     Test-CPAN-Meta
version:                  0.23
abstract:                 Validate your CPAN META.yml files
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  Parse::CPAN::Meta:      0.02
  Test::Builder:          0
recommends:
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70
  Test::Builder::Tester:  0

provides:
  Test::CPAN::Meta:
    file:     lib/Test/CPAN/Meta.pm
    version:  0.23
  Test::CPAN::Meta::Version:
    file:     lib/Test/CPAN/Meta/Version.pm
    version:  0.23
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-CPAN-Meta
  repository: http://github.com/barbie/Test-CPAN-Meta

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
